---
title: "PASC-analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PASC-analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mlho)
```

## How to create the 5 post-acute sequelae of sars-cov-2 infection (pasc)  

First thing is to load the 2.1 data plus the ICD-10-phecode mapping file that comes with the package 
*4-digit ICD-10 codes are needed for mapping*

```{r}
# data(pHE_map)
# force(phe_map_unique)
# PatientObservations <- read_csv(file.choose())
# PatientClinical <- read_csv(file.choose())
# PatientSummary <- read_csv(file.choose())
```


Then, run the function (it'll take a few minutes depending on the size of the data)
```{r}
# test_run <- pasccases(PatientObservations,PatientClinical,PatientSummary,loyaltydays1=90)
```

Results would be as follows:.
```{r}
# test_run$analysis1plot ##case 1 bubble chart
# test_run$analysis2plot
# test_run$analysis3plot
# test_run$analysis4plot
# case5_pre <- test_run$analysis5_pre
# case5_preduri <- test_run$analysis5_preduri
```

